name: lint

on:
  pull_request_target:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: checkout 
      uses: actions/checkout@v3
    - name: plugin-lint 
      uses: docker://codingci/plugin-lint:latest      
    - name: markdown-lint 
      uses: docker://tencentcom/markdown-lint:latest
    - name: notify
      uses: docker://tencentcom/wecom-message:latest
      env:
        PLUGIN_ROBOT: ${{ secrets.WEWORK_BOT }}
        PLUGIN_CONTENT: |
          [https://github.com/${{ github.repository }}/pulls](https://github.com/${{ github.repository }}/pulls)

          
          走查代码啦~ for <@${{ github.actor }}>


