name: md-lint

on:
  pull_request:
    branches:
    - main

jobs:
  md-lint:
    runs-on: ubuntu-latest
    steps:
    - name: checkout 
      uses: actions/checkout@v3
    - name: lint 
      uses: docker://tencentcom/markdown-lint:latest

